services:
  homeboard:
    build: .
    # comment the build and use the published image instead
    # image: ghcr.io/lepicodon/homeboard:latest
    container_name: homeboard
    restart: unless-stopped
    mem_limit: 128m
    ports:
      - '3000:3000'
    volumes: # using a Docker volume for simplicity
      - homeboard-data:/data:rw
    environment:
      - PORT=3000
      - DB_PATH=/data/homeboard.db
    # labels:
      # - traefik.enable=true

volumes:
  homeboard-data:
